basePath: /api/v1
definitions:
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.User:
    properties:
      balance:
        type: number
      name:
        type: string
      "no":
        type: integer
      status:
        type: boolean
    type: object
  model.UserResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: guuakashsm@gmail.com
    name: Guru Akash
    url: https://github.com/GURUAKASH-MUTHURAJAN
  description: Sample description
  title: Documenting API (Your API Title)
  version: "1"
paths:
  /users:
    get:
      description: return list of all user fom the database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: return list of all
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: create and return user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: return created user
      tags:
      - Users
swagger: "2.0"
